### ISSUE TITLE
/nbttile command-colors not working

### ISSUE THREAD

**Issue by coin3x** [goncalomb/NBTEditor#2]
Version: Spigot 1.9
Plugin Version: 2.0 Snapshot
When I look at a command block and type this command, it keeps saying "No Command Block in sight".

**Comment by goncalomb** [comment]
Were you using one of the new types of command block?

The new types of command blocks are not supported. Basically Bukkit doesn't recognize them as command blocks yet. It would be possible to write some hack to make it work, but we'll wait for Bukkit to catch up.

**Comment by coin3x** [comment]
Alright :)

**Comment by goncalomb** [comment]
The problem with the new Command Blocks was fixed by Spigot ([SPIGOT-2285](https://hub.spigotmc.org/jira/browse/SPIGOT-2285), [Bukkit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/329ef57aea4529ce36b9d59b22d2ce00d1c64cb0), [CraftBukkit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/4e19de129580f7e2e9bf10734e09d3dbc3ca9722)).

I'm fixing it on the NBTEditor side.
