### ISSUE TITLE
/bos items

### ISSUE THREAD

**Issue by tuanhp0** [goncalomb/NBTEditor#24]
it does not work
I just downloaded your file and started the server, I used up all the commands
But there is a problem when I use /bos items I can put the item into the box, but not saved
Can you show me how to fix this?thanks

**Comment by goncalomb** [comment]
What version of the NBTEditor and Bukkit are you using? Do you see any error on the console? Do other commands (like `/bos var`) work?

I assume that you are not on 1.13 because `/bos items` was removed on the latest versions. Normally I don't fix older versions, but I may be able to help if you provide some more information.

**Comment by tuanhp0** [comment]
already know the error from my server, thank you

Vào Th 2, 17 thg 9, 2018 vào lúc 06:04 Gonçalo Baltazar <
notifications@github.com> đã viết:
